### ISSUE TITLE
Dress segmentation 

### ISSUE THREAD

**Issue by deep1blue** [cerlymarco/MEDIUM_NoteBook#1]
@cerlymarco kudos! amazing work (dress segmentation) on combining GMM and autoencoders to get the mask of an image! I was replicating your approach from the notebook you have put up and couldn't find the fashion_unet.h5 model to replicate the results. Will it be possible to share the trained model with us, please. Thank you!

**Comment by cerlymarco** [comment]
Hi, At the moment I can't share the dataset and the trained model (due to business reasons). As you just say, you can find the full code in the repository. The dataset is easy to recreate scraping in internet: the dataset I cited on kaggle (in my article) is also a good starting point. The training time is proportional to the amount of images you have at disposal; I suggest you to use Colab at this step.
All the best

**Comment by deep1blue** [comment]
ok thanks!
