### ISSUE TITLE
Why do you create smoother iteratively?

### ISSUE THREAD

**Issue by MemphisMeng** [cerlymarco/MEDIUM_NoteBook#21]
I think it is okay to initialize a smoother at the very beginning and then just use it for the rest, which looks like this:
```
smoother = ConvolutionSmoother(window_len=window_len, window_type='ones')
# smoother = ExponentialSmoother(window_len=window_len, alpha=0.4)

for i in tqdm(range(timesteps + 1), total=(timesteps + 1)):
    if i > window_len:

        # smoother.smooth(series['original'][:, -window_len-1:])
        smoother.smooth(series['original'][:,-window_len:])

        series['smooth'] = np.hstack([series['smooth'], smoother.smooth_data[:,[-1]]]) 

        _low, _up = smoother.get_intervals('sigma_interval', n_sigma=2)
        series['low'] = np.hstack([series['low'], _low[:,[-1]]])
        series['up'] = np.hstack([series['up'], _up[:,[-1]]])

        is_anomaly = np.logical_or(
            series['original'][:,-1] > series['up'][:,-1], 
            series['original'][:,-1] < series['low'][:,-1]
        ).reshape(-1,1)
        
        if is_anomaly.any():
            series['ano_id'] = np.hstack([series['ano_id'], is_anomaly*i]).astype(int)
    
    if i>=timesteps:
        continue
    
    series['original'] = np.hstack([series['original'], data['pv'].values.reshape(1, -1)[:,[I]]])
```
Perhaps I missed something, can you tell us more about your logic?

**Comment by cerlymarco** [comment]
Every time a new observation comes you need to recompute the smoothing on the series composed of history and the new observation. These smoothers are not like sklearn models that you fitted and the use at the inference time calling predict. Fortunately, this operation is not heavy because the smoothers available in tsmoothie are optimized to run fast exactly for these cases.

I provided the code you used only as a reference. Maybe there better ways to write it (initialize the smoother first and then call smooth recomputea the smoothing every time forgetting the past) or maybe it not adapts to all the cases but the important thing to remember is what I introduced before
