### ISSUE TITLE
librosa

### ISSUE THREAD

**Issue by TDL77** [cerlymarco/MEDIUM_NoteBook#48]
in notebook :
https://github.com/cerlymarco/MEDIUM_NoteBook/tree/master/Predictive_Maintenance_CRNN
https://github.com/cerlymarco/MEDIUM_NoteBook/tree/master/Predictive_Maintenance_ResNet

in sample_mfcc = librosa.feature.mfcc(np.asfortranarray(sample),sr=40000)
and 
sample_spectre = np.apply_along_axis(lambda x: librosa.feature.melspectrogram(x,sr=40_000) ,0, sample)
..... same errore
TypeError: melspectrogram() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given
TypeError: mfcc() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given

**Comment by cerlymarco** [comment]
Hi, 

as stated by the error, you must specify all the arguments

example:
`np.apply_along_axis(lambda x: librosa.feature.melspectrogram(y=x,sr=40), 0, sample)`

instead of:
`np.apply_along_axis(lambda x: librosa.feature.melspectrogram(x,sr=40), 0, sample)`

if u support the project, don't forget to leave a star ;-)
