### ISSUE TITLE
Question for extreme time series forecasting

### ISSUE THREAD

**Issue by debmalya97** [cerlymarco/MEDIUM_NoteBook#9]
Thank you for the great tutorial! I didn't understand the logic of how did you merge the time series of different cities and made them into one and then fed into the model. I am working with a similar dataset where I have time series of different cities. I am taking the time series of each city separately and training the model. I start fresh for a different city. I wanted to make one heterogeneous model which takes the data of all the cities together.

Thank you in advance!
deb

**Comment by cerlymarco** [comment]
Hi, first of all, you have to define your validation strategy... In my tutorial I test to the goodness of my model on the last x% of the series at my disposal; in this way, you operate a division among train and test. Then if you want to fit a sequence model (like GRU/LSTM) you have to arrange your data into sequences. To do this remember to keep the series of cities separate for train and test in order to avoid overlapping mistakes. In the end you can feed the model with all your train sequences. You can visualize results on test operating partition among groups/cities.

Remember to stay connected on [Medium](https://medium.com/@cerlymarco) and on GitHub... All the best

**Comment by debmalya97** [comment]
Hey
Thanks for the prompt reply. I wanted to ask for a particular date all the cities will have different values of Average price? My question is how are you combining the data of all the cities because when you feed the data to the model it should have one value for a particular time right?

**Comment by cerlymarco** [comment]
Hopefully, they have different values. You have to take care only on the way you build your sequences and about the separation among train and test; it doesn't matter the order of the sequences used to feed the model. One sequence of multiple timesteps refers to particular timestamps (your average target values if the output is univariate).

Stay tuned. Marco

**Comment by debmalya97** [comment]
thank you so much for the reply. So according to my understanding, you are clubbing the data of different regions and feeding into the system.  So now to forecast the data is it forecasting citywise or a general forecast?

**Comment by cerlymarco** [comment]
In my case, I produce one model for all. You can retrieve the city-level performance and so on at the end

**Comment by debmalya97** [comment]
Thanks!.. Could you please tell me how to get city wise results ?

**Comment by cerlymarco** [comment]
I don't know how your data look like but in my notebook, I arrange my data in order to extract this information and all the KPIs I need. Bye
